<a href="https://colab.research.google.com/github/FMK2312/Summer-Training-for-III-year/blob/main/Day1/Data%20Pre-processing/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

importing libraries required to run code
1) importing numpy as np. Numpy is used to manipulate data
2) importing matplotlib for plotting
3) importing pandas to load data and preprocess

## Importing the dataset

In [22]:
dataset = pd.read_csv('sample_data/Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

here we have imported our data file 'Data.csv'
We have assigned our Independent variable to X, which are first 3 columns of our data. [:,:-1] the first range is for selecting rows, as we have not provided any range it will select all the rows. Second range is for columns, here we have provided range :-1 which means we want all the column but not the last one.

We have assigned our dependent variable to Y. we have only one dependent variable which is the last column.

In [23]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Here we can see our Independent Variables. Country, Age, Salary.
These are Independent variable as there is no correlation and association between them. For ex, we cannot determine country from age and vice versa.

In [24]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Y is our dependent variable. This is dependent as we calculated Y from X.

## Taking care of missing data

In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

Scikit learn or sklearn is an open source library. It features various classification, regression and clustering algorithms.
Now, if we analyze our data, i.e X, we can see that at some places we have NaN i.e missing values in rows. Missing values need to be removed or handled as they can affect the performance of our model.
Removing a row leads to loss of data, which leads to its own complications.
What we can do is impute the missing values (infer them from existing values in columns). We will do this by using sklearn's impute module from which we will use SimpleImputer ftn.
SimpleImputer is an Univariate feature imputer, which means we impute the missing values using the non missing values of that column itself where missing values are present.
We will impute the columns 1 and 2.
first we will fit our imputer with the data and then transform the columns using the imputer.
Here we are using 'mean' as our strategy that is we are replacing our NaN values with mean of non missing values.

In [26]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Here we can see we have no NaN values. 

## Encoding categorical data

### Encoding the Independent Variable

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Here we can see in our data that we have categorical data present, that is, Country names.
Models only work with numerical values. For this reason, it is necessary to convert the categorical values of the features into numerical ones, So the machine can learn from those data and gives the right model. This process of converting categorical data into numerical data is called Encoding.
We are using ColumnTransformer from sklearn.compose to transform our categorical data column ie Country to numerical one.
We will use OneHotEncoder() from sklearn.preprocessing to transform our column, we will pass this ftn as a param to set of params of ColumnTransfromer.
Now lets take a look at Params of ColumnTransformer. 1) Transformers 
this specifies the type of transformation in this case, 'encoder', the ftn we using for this, 'OneHotEncoder()'. last one is Index of column we want to transform. 
2) remainder - this specifies what to do with the rest of columns. set to 'passthrough' we just concanate the colummns with the output of transformer. set to 'drop' we just drop all columns but the transformed one.


In [28]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Here we are using LabelEnoder to transform the categorical data (Yes/No) into 0/1.

In [30]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


OneHotEncoding vs LabelEncoding


LabelEncoding encodes the given column in the range of 0 - number of Classes-1. Now suppose we encoded our country column using LabelEncoder,
we will assign each different country a number from 0 -> 2
so for example france becomes 1, spain 0 etc. This is very straight forward right? it is. but it raises another problem. because we have labelencoded our independent categorical data, we have different numbers ranging from 0 -> 2 in the same column. bcz of this, the model will misunderstand the data to be in some kind of order, 0 < 1 < 2. But this isn’t the case at all. This sort of ranks the country, and our model will learn from this and give wrong prediction. So to avoid this, we never label encode our independent variables, only dependent variables.

OneHotEncoding is done on independent variables. What one hot encoding does is, it takes a column which has categorical data, which has been label encoded, and then splits the column into multiple columns(basically we split a column into multiple depending on different categories present). The numbers are replaced by 1s and 0s, depending on which column has what value. In our example, we’ll get three new columns, one for each country — France, Germany, and Spain.

For rows which have the first column value as France, the ‘France’ column will have a ‘1’ and the other two columns will have ‘0’s. Similarly, for rows which have the first column value as Germany, the ‘Germany’ column will have a ‘1’ and the other two columns will have ‘0’s.








## Splitting the dataset into the Training set and Test set

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

This step is very straight forward. We are just splitting our data set into training and testing datasets, in the ratio of 8:2.
The param random_state=1 in train_test_split splits the datasets into same data for every random_state set to 1.

In [32]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [33]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [34]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [35]:
print(y_test)

[0 1]


## Feature Scaling

In [36]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

Feature scaling is the process of normalising the range of features in a dataset.
Feature scaling through standardization (or Z-score normalization) can be an important preprocessing step for many machine learning algorithms. 
Feature scaling is of two types normalisation and standardization.


Here we have used StandardScaler of sklearn, which is an example of standardization. Standardization involves rescaling the features such that they have the properties of a standard normal distribution with a mean of zero and a standard deviation of one.

MinMaxScaler on other hand is an example of normalisation. Normalization scales values between 0 and 1. This has application in neural networks where we recognize an object based on features. 

One important thing to notice here is, we have not fit our test dataset, we have just transformed it. 

This is a standard procedure when we scale our data. we use fit_transform() on our training data and transform() on our test data.

If we will use the fit method on our test data too, we will compute a new mean and variance that is a new scale for each feature and will let our model learn about our test data too. Thus, what we want to keep as a surprise is no longer unknown to our model and we will not get a good estimate of how our model is performing on the test (unseen) data which is the ultimate goal of building a model using machine learning algorithm.

fit_transform() is used on the training data so that we can scale the training data and also learn the scaling parameters of that data. Here, the model built by us will learn the mean and variance of the features of the training set. These learned parameters are then used to scale our test data. The fit method is calculating the mean and variance of each of the features present in our data. The transform method is transforming all the features using the respective mean and variance.

Now, we want scaling to be applied to our test data too and at the same time do not want to be biased with our model. We want our test data to be a completely new and a surprise set for our model. The transform method helps us in this case.

Using the transform method we can use the same mean and variance as it is calculated from our training data to transform our test data. Thus, the parameters learned by our model using the training data will help us to transform our test data.


In [37]:
print(X_train)

[[0.0 0.0 1.0 0.5120772946859904 0.11428571428571432]
 [0.0 1.0 0.0 0.5652173913043479 0.45079365079365075]
 [1.0 0.0 0.0 0.7391304347826089 0.6857142857142855]
 [0.0 0.0 1.0 0.4782608695652175 0.37142857142857144]
 [0.0 0.0 1.0 0.0 0.0]
 [1.0 0.0 0.0 0.9130434782608696 0.8857142857142857]
 [0.0 1.0 0.0 1.0 1.0]
 [1.0 0.0 0.0 0.34782608695652173 0.2857142857142856]]


In [38]:
print(X_test)

[[0.0 1.0 0.0 0.1304347826086958 0.17142857142857149]
 [1.0 0.0 0.0 0.43478260869565233 0.5428571428571427]]
